[package]
name = "c10k-wca"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "app"
path = "src/main.rs"

[dependencies]
wca = { git = "https://github.com/f01dab1e/wTools.git", branch = "f0kek" }
ra_ap_profile = "0.0.166"
